### ISSUE TITLE
Public URL

### ISSUE THREAD

**Issue by eric-brechemier** [medialab/medea_website#1]
When do you plan to share this website publicly? Do you have a public URL to view or preview the site yet?

**Comment by legaultpierre** [comment]
Hi Eric,

There is no preview for the moment, but I'll let you know as soon as there is one

**Comment by eric-brechemier** [comment]
@legaultpierre Thanks :)

**Comment by eric-brechemier** [comment]
I found it:
http://medea.medialab.sciences-po.fr/#/

I close the issue.
